sudo: false
language: rust
rust:
    - beta
    - nightly
    - stable
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - export CXX="g++-4.8" CC="gcc-4.8"
  - cargo test
  - cargo doc
notifications:
  webhooks: http://build.servo.org:54856/travis
